---
policies: ./policies.yml

plays:
   - name: "CIS 1.1"
     policies:
       - "recent root password usage"
       - "recent root access key usage"
   - name: "CIS 1.2"
     policies:
       - "users with password and without MFA"
   - name: "CIS 1.3"
     policies:
       - "users with password not used in 90 days"
       - "users with active access key not used in 90 days"
   - name: "CIS 1.4"
     policies:
       - "ensure access keys are rotated every 90 days"
   - name: "CIS 1.5"
     policies:
       - "ensure IAM password policy requires at least one uppercase letter"
   - name: "CIS 1.6"
     policies:
       - "ensure IAM password policy require at least one lowercase letter"
   - name: "CIS 1.7"
     policies:
       - "ensure IAM password policy require at least one symbol"
   - name: "CIS 1.8"
     policies:
       - "ensure IAM password policy require at least one number"
   - name: "CIS 1.9"
     policies:
       - "ensure IAM password policy requires minimum length of 14 or greater"
   - name: "CIS 1.10"
     policies:
       - "ensure IAM password policy prevents password reuse"
   - name: "CIS 1.11"
     policies:
       - "ensure IAM password policy expires passwords within 90 days or less"
   - name: "CIS 1.12"
     policies:
       - "ensure no root account access key exists"
   - name: "CIS 1.13"
     policies:
       - "ensure MFA is enabled for the root account"
   - name: "CIS 1.14"
     policies:
       - "ensure hardware MFA is enabled for the root account"
   - name: "CIS 1.16"
     policies:
       - "ensure IAM policies are attached only to groups or roles (Inline)"
   - name: "CIS 1.16"
     policies:
       - "ensure IAM policies are attached only to groups or roles (Attached)"
   - name: "CIS 1.18"
     policies:
       - "ensure IAM Master role is active"
   - name: "CIS 1.18"
     policies:
       - "ensure IAM Manager role is active"
   - name: "CIS 1.22"
     policies:
       - "ensure a support role has been created to manage incidents with AWS Support"
   - name: "CIS 1.23"
     policies:
       - "Do not setup access keys during initial user setup for all IAM users that have a console password"
   - name: "CIS 1.24"
     policies:
       - "ensure IAM policies that allow full \"*:*\" administrative privileges are not created"
   - name: "CIS 2.1"
     policies:
       - "ensure CloudTrail is enabled in all regions"
   - name: "CIS 2.2"
     policies:
       - "ensure CloudTrail log file validation is enabled"
   - name: "CIS 2.3"
     policies:
       - "ensure the S3 bucket CloudTrail logs to is not publicly accessible"
   - name: "CIS 2.4"
     policies:
       - "ensure CloudTrail trails are integrated with CloudWatch Logs"
   - name: "CIS 2.5"
     policies:
       - "ensure AWS Config is enabled in all regions (all resource Types)"
       - "ensure AWS Config is enabled in all regions (global resource types)"
       - "ensure AWS Config is enabled in all regions (s3 bucket defined)"
       - "ensure AWS Config is enabled in all regions (sns topic defined)"
   - name: "CIS 2.6"
     policies:
       - "ensure S3 bucket access logging is enabled on the CloudTrail S3 bucket"
   - name: "CIS 2.7"
     policies:
       - "ensure CloudTrail logs are encrypted at rest using KMS CMKs"
   - name: "CIS 2.8"
     policies:
       - "ensure rotation for customer created CMKs is enabled"
   - name: "CIS 3.1"
     policies:
       - "ensure a log metric filter and alarm exist for unauthorized API calls"
   - name: "CIS 3.2"
     policies:
       - "ensure a log metric filter and alarm exist for Management Console sign-in without MFA"
   - name: "CIS 3.3"
     policies:
       - "ensure a log metric filter and alarm exist for usage of root account"
   - name: "CIS 3.4"
     policies:
       - "ensure a log metric filter and alarm exist for IAM policy changes"
   - name: "CIS 3.5"
     policies:
       - "ensure a log metric filter and alarm exist for CloudTrail configuration changes"
   - name: "CIS 3.6"
     policies:
       - "ensure a log metric filter and alarm exist for AWS Management Console authentication failures"
   - name: "CIS 3.7"
     policies:
       - "ensure a log metric filter and alarm exist for disabling or scheduled deletion of customer created CMKs"
   - name: "CIS 3.8"
     policies:
       - "ensure a log metric filter and alarm exist for S3 bucket policy changes"
   - name: "CIS 3.9"
     policies:
       - "ensure a log metric filter and alarm exist for AWS Config configuration changes"
   - name: "CIS 3.10"
     policies:
       - "ensure a log metric filter and alarm exist for security group changes"
   - name: "CIS 3.11"
     policies:
       - "ensure a log metric filter and alarm exist for changes to Network Access Control Lists (NACL)"
   - name: "CIS 3.12"
     policies:
       - "ensure a log metric filter and alarm exist for changes to network gateways"
   - name: "CIS 3.13"
     policies:
       - "ensure a log metric filter and alarm exist for route table changes"
   - name: "CIS 3.14"
     policies:
       - "ensure a log metric filter and alarm exist for VPC changes"
   - name: "CIS 4.1"
     policies:
       - "ensure no security groups allow ingress from 0.0.0.0/0 to port 22"
   - name: "CIS 4.2"
     policies:
       - "ensure no security groups allow ingress from 0.0.0.0/0 to port 3389"
   - name: "CIS 4.3"
     policies:
      - "ensure VPC flow logging is enabled in all VPCs"
   - name: "CIS 4.4"
     policies:
       - "ensure the default security group of every VPC restricts all traffic"
